"""Add database tables"""

import sqlalchemy as sa
from alembic import op

revision = "aa73ee260666"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=True)
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("quality", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "factors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "asset_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.CheckConstraint(
            "adjusted_close > 0 AND low > 0 AND high >= low AND open >= low AND open <= high AND close >= low AND close <= high"
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "asset_id", "date"),
    )
    op.create_index(op.f("ix_asset_prices_asset_id"), "asset_prices", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_asset_prices_dataset_id"), "asset_prices", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_asset_prices_date"), "asset_prices", ["date"], unique=False)
    op.create_table(
        "benchmark_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.CheckConstraint("adjusted_close > 0"),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "asset_id", "date"),
    )
    op.create_index(
        op.f("ix_benchmark_prices_dataset_id"), "benchmark_prices", ["dataset_id"], unique=False
    )
    op.create_table(
        "factor_returns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("factor_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["factor_id"],
            ["factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "factor_id", "date"),
    )
    op.create_index(
        op.f("ix_factor_returns_dataset_id"), "factor_returns", ["dataset_id"], unique=False
    )
    op.create_index(op.f("ix_factor_returns_date"), "factor_returns", ["date"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("methodology", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_runs_dataset_id"), "research_runs", ["dataset_id"], unique=False
    )
    op.create_table(
        "risk_free_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.CheckConstraint("rate > -1"),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dataset_id", "date"),
    )
    op.create_table(
        "analytics_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_results_run_id"), "analytics_results", ["run_id"], unique=False
    )
    op.create_table(
        "backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=40), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "portfolio_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.CheckConstraint("weight >= 0 AND weight <= 1"),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("portfolio_id", "asset_id"),
    )
    op.create_index(
        op.f("ix_portfolio_positions_portfolio_id"),
        "portfolio_positions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "backtest_returns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("gross", sa.Float(), nullable=False),
        sa.Column("net", sa.Float(), nullable=False),
        sa.Column("turnover", sa.Float(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("backtest_id", "date"),
    )
    op.create_index(
        op.f("ix_backtest_returns_backtest_id"), "backtest_returns", ["backtest_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_returns_backtest_id"), table_name="backtest_returns")
    op.drop_table("backtest_returns")
    op.drop_index(op.f("ix_portfolio_positions_portfolio_id"), table_name="portfolio_positions")
    op.drop_table("portfolio_positions")
    op.drop_table("backtests")
    op.drop_index(op.f("ix_analytics_results_run_id"), table_name="analytics_results")
    op.drop_table("analytics_results")
    op.drop_table("risk_free_rates")
    op.drop_index(op.f("ix_research_runs_dataset_id"), table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_factor_returns_date"), table_name="factor_returns")
    op.drop_index(op.f("ix_factor_returns_dataset_id"), table_name="factor_returns")
    op.drop_table("factor_returns")
    op.drop_index(op.f("ix_benchmark_prices_dataset_id"), table_name="benchmark_prices")
    op.drop_table("benchmark_prices")
    op.drop_index(op.f("ix_asset_prices_date"), table_name="asset_prices")
    op.drop_index(op.f("ix_asset_prices_dataset_id"), table_name="asset_prices")
    op.drop_index(op.f("ix_asset_prices_asset_id"), table_name="asset_prices")
    op.drop_table("asset_prices")
    op.drop_table("factors")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
